name: test

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, reopened, edited]

permissions: {}

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      memcached:
        image: memcached
        ports:
          - 11211:11211
      redis:
          image: redis
          ports:
            - 6379:6379
    steps:
      - name: setup-repos
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683

      - name: setup-go
        uses: actions/setup-go@0aaccfd150d50ccaeb58ebd88d36e91967a5f35b

      - name: run-tests
        run: |
          go vet .
          go test -v -race ./...
